### ISSUE TITLE
ActiveUser missing userName after restoring session

### ISSUE THREAD

**Issue by daniel-bsci** [Kinvey/Kinvey-Xamarin#79]

**Comment by vinaygahlawat** [comment]
Sorry for the delay in response, and thank you for filing this issue.  We have reproduced this as well, and have opened a ticket to fix this.  ETA for this fix is early next week, and this issue will be updated when it is available.

**Comment by vinaygahlawat** [comment]
Issue resolved with #84 and available in the Beta-07 release.
