### ISSUE TITLE
Handle http error status codes from custom endpoints

### ISSUE THREAD

**Issue by daniel-bsci** [Kinvey/Kinvey-Xamarin#80]
It would be nice to be able to handle http 4xx/5xx error codes gracefully with custom endpoint. Currently the SDK tries to parse the expected success response body even though an error code was returned (such as 404).

**Comment by vinaygahlawat** [comment]
Thank you for filing this issue.  We have reproduced this issue, and have opened up a ticket for it.  The estimated ETA for this fix is early next week.

**Comment by vinaygahlawat** [comment]
Issue resolved with #85 and available in the Beta-07 release.  Status code for custom endpoints is now available with the `KinveyException` thrown.
